num1 = eval(input("Please enter a number:"))
num2 = eval(input("Please enter another number:"))

print("\nThe sum of" , num1 , " and " , num2, " is " , num1 + num2)
print("The difference of" , num1 , " and "  , num2 , " is " , num1 - num2)
print("The product of" , num1 , " and "  , num2 , " is " , num1 * num2)
print("The quotient of" , num1 , " and "  , num2 , " is " , num1 / num2)
print("The exponent of" , num1 , " and "  , num2 , " is " , num1 ** num2)
print("The remainder of" , num1 , " and "  , num2 , " is " , num1 % num2)
print("The floor division of" , num1 , " and "  , num2 , " is " , num1 // num2)